# Generated by Django 5.2.8 on 2025-11-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, verbose_name='IMEI')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('passport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер паспорта')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В обработке'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
